<!-- Formulaire de création de salon -->
<div id="createSalonForm">
    <form method="post" action="index.php?action=createNewSalon">
        <label for="salonName">Nom du salon :</label>
        <input type="text" id="salonName" name="SalonName" placeholder="Nom du salon" required>
        
        <!-- Champ caché pour l'ID de la catégorie -->
        <input type="hidden" name="CategorieId" value="<?= $_POST['CategorieId'] ?>">
        
        <button type="submit">Créer le salon</button>
    </form>
</div>