<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Distorsion</title>
    <link rel="stylesheet" href="public/style.css"> 
</head>
<body>
    <header class="header">
        <div class="logo">
            <img src="public/img/logo.png" alt="Logo Distorsion">
        </div>
        <div class="title">
            <h1>Distorsion</h1>
        </div>
        <nav class="navigation">
            <a href="index.php?action=redirectToChat">Chat</a>
            <a href="index.php?action=goToAbout">À propos</a>
        </nav>
    </header>
    <main>
        <?php include $template ?>
    </main>
</body>
</html>